site_name: Better Every Loop
site_description: A blog written by Jacob Strauss
site_url: https://jda5.github.io/blog/

theme:
 # Custom logo icon (appears in top-left corner)
  logo: assets/logo.png
  favicon: assets/favicon.ico
  name: material
  
  # ---------------------------------------- color scheme configuration
  palette:
    scheme: default
    primary: amber
    accent: yellow

  # ---------------------------------------- font configuration
  font:
    text: Exo
    code: Roboto Mono
  
  # Feature flags - these enable specific UI behaviors
  features:
    - navigation.indexes      # Allows section index pages
    - navigation.top          # Adds "back to top" button when scrolling
    - navigation.tabs         # Shows top-level sections as tabs in header
    - navigation.footer       # Adds prev/next page links at bottom
    - search.suggest          # Shows search suggestions as you type
    - search.highlight        # Highlights search terms in results
    - content.code.copy       # Adds copy button to code blocks
    - content.code.annotate   # Allows adding annotations to code
  
plugins:
  - search  # Enables the search functionality
  
  # Blog plugin configuration
  - blog:
      authors_file: .authors.yml           # Where author profiles are stored
      blog_dir: .                          # Root directory for blog posts
      blog_toc: true                       # Show table of contents on blog posts
      archive_date_format: yyyy            # How dates appear in archives (e.g., "2024")
      categories_allowed:                  # Whitelist of categories you'll use
        - Business
        - Software
      post_excerpt: required                # Requires an excerpt for each post
      post_excerpt_separator: <!-- more --> # Where to cut off the preview
  
  # Tags plugin - helps organize posts by topics
  - tags:
      tags_file: tags.md  # Creates a dedicated page listing all tags
  
  # RSS feed generation
  - rss:
      match_path: "posts/.*"  # Only include files in posts/ directory
      date_from_meta:
        as_creation: date.created  # Uses this frontmatter field for creation date
        as_update: date.updated    # Uses this frontmatter field for update date

# Extra settings
extra:
  social:  # Social media links shown in footer
    - icon: fontawesome/brands/github
      name: Jacob Strauss on GitHub
      link: https://github.com/jda5

    - icon: fontawesome/brands/linkedin
      name: Jacob Strauss on LinkedIn
      link: https://www.linkedin.com/in/jacob-strauss-699546196

  generator: false  # Removes "Made with Material for MkDocs" from footer

hooks:
  - hooks/socialmedia.py  # Custom hook for social media card generation

# Markdown extensions - add functionality to your markdown
markdown_extensions:
  - attr_list  # Allows adding HTML attributes to markdown elements
  
  # Emoji support (e.g., :smile: becomes 😊)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - tables     # Enables markdown tables
  - md_in_html # Allows markdown inside HTML blocks
  
  - pymdownx.blocks.caption  # Adds captions to images/figures
  
  # Admonitions - creates callout boxes (tip, warning, note, etc.)
  - admonition
  - pymdownx.details      # Makes admonitions collapsible
  - pymdownx.superfences  # Enhanced code blocks with syntax highlighting
  
  # Tabbed content - creates tabbed interfaces in your posts
  - pymdownx.tabbed:
      alternate_style: true  # Uses modern tab styling

# Site navigation structure
nav:
  - Home: index.md
  - About: author/jacob.md
  - Tags: tags.md