site_name: Better Every Loop
site_description: A blog written by Jacob Strauss
site_url: http://www.example.com

theme:
  name: material
  
  # ---------------------------------------- color scheme configuration
  palette:

    # Light mode (default)
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode (optional)
    # - scheme: slate
    #   primary: indigo
    #   accent: indigo
    #   toggle:
    #     icon: material/brightness-4  # Moon icon to represent dark mode
    #     name: Switch to light mode
  
  # Typography settings
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  
  # Feature flags - these enable specific UI behaviors
  features:
    - navigation.indexes      # Allows section index pages (you already had this)
    - navigation.top          # Adds "back to top" button when scrolling
    - navigation.tabs         # Shows top-level sections as tabs in header
    - navigation.sections     # Groups navigation items into collapsible sections
    - navigation.footer       # Adds prev/next page links at bottom
    - search.suggest          # Shows search suggestions as you type
    - search.highlight        # Highlights search terms in results
    - content.code.copy       # Adds copy button to code blocks
    - content.code.annotate   # Allows adding annotations to code (comments with numbers)
  
  # Custom logo icon (appears in top-left corner)
  icon:
    logo: material/book-open-page-variant  # You can change this to any Material Design icon

plugins:
  - search  # Enables the search functionality
  
  # Blog plugin configuration
  - blog:
      authors_file: .authors.yml           # Where author profiles are stored
      authors_profiles: true               # Show author profile pages
      blog_dir: .                          # Root directory for blog posts
      blog_toc: true                       # Show table of contents on blog posts
      archive_date_format: MMMM yyyy       # How dates appear in archives (e.g., "January 2024")
      categories_allowed:                  # Whitelist of categories you'll use
        - Business
        - Software
      post_excerpt: required                # Requires an excerpt for each post
      post_excerpt_separator: <!-- more --> # Where to cut off the preview
  
  - meta  # Allows setting metadata in separate .meta.yml files
  
  # Tags plugin - helps organize posts by topics
  - tags:
      tags_file: tags.md  # Creates a dedicated page listing all tags
  
  # RSS feed generation
  - rss:
      match_path: "posts/.*"  # Only include files in posts/ directory
      date_from_meta:
        as_creation: date.created  # Uses this frontmatter field for creation date
        as_update: date.updated    # Uses this frontmatter field for update date

# Extra settings
extra:
  social:  # Social media links shown in footer
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk
  
  generator: false  # Removes "Made with Material for MkDocs" from footer

hooks:
  - hooks/socialmedia.py  # Custom hook for social media card generation

# Markdown extensions - add functionality to your markdown
markdown_extensions:
  - attr_list  # Allows adding HTML attributes to markdown elements
  
  # Emoji support (e.g., :smile: becomes 😊)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - tables     # Enables markdown tables
  - md_in_html # Allows markdown inside HTML blocks
  
  - pymdownx.blocks.caption  # Adds captions to images/figures
  
  # Admonitions - creates callout boxes (tip, warning, note, etc.)
  - admonition
  - pymdownx.details      # Makes admonitions collapsible
  - pymdownx.superfences  # Enhanced code blocks with syntax highlighting
  
  # Tabbed content - creates tabbed interfaces in your posts
  - pymdownx.tabbed:
      alternate_style: true  # Uses modern tab styling

# Site navigation structure
nav:
  - Home: index.md